name: New Processing Request
description: Suggest a new Bioproject or SRA Study for processing
title: "[Study] "
labels: ["New", "Needs Triage"]
body:
- type: input
  attributes:
    label: Accession
    description: |
      The PRJ, SRP, or Pubmed accession
      examples:
        - SRP000123
        - PRJNA000123
        - 300000123
  validations:
    required: true